### ISSUE TITLE
o3d3xx-h5 node dies immediately

### ISSUE THREAD

**Issue by jbdss** [ifm/o3d3xx-h5#2]
When I launch  using roslaunch o3d3xx_h5 h5writer.launch I get the following result:

started roslaunch server http://dss1:41319/

SUMMARY
========

PARAMETERS
 * /o3d3xx_h5/h5writer/circular_buffer_sz: 999999999
 * /o3d3xx_h5/h5writer/compression: 9
 * /o3d3xx_h5/h5writer/open_mode: w-
 * /o3d3xx_h5/h5writer/outdir: /tmp
 * /o3d3xx_h5/h5writer/outfile: o3d3xx.h5
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /o3d3xx_h5/
    h5writer (o3d3xx_h5/h5writer)

auto-starting new master
process[master]: started with pid [12824]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 73046828-35d4-11e7-81e2-a0c589016c88
process[rosout-1]: started with pid [12837]
started core service [/rosout]
process[o3d3xx_h5/h5writer-2]: started with pid [12845]
Traceback (most recent call last):
  File "/home/dss/dev/o3d3xx-h5-catkin/src/o3d3xx_h5/bin/h5writer", line 4, in <module>
    from o3d3xx_h5 import H5Writer
  File "/home/dss/dev/o3d3xx-h5-catkin/devel/lib/python2.7/dist-packages/o3d3xx_h5/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 86, in <module>
  File "/home/dss/dev/o3d3xx-h5-catkin/src/o3d3xx_h5/src/o3d3xx_h5/_H5Writer.py", line 30, in <module>
    from o3d3xx.srv import Dump
ImportError: No module named o3d3xx.srv
[o3d3xx_h5/h5writer-2] process has died [pid 12845, exit code 1, cmd /home/dss/dev/o3d3xx-h5-catkin/src/o3d3xx_h5/bin/h5writer /xyz_image:=/o3d3xx/camera/xyz_image /amplitude:=/o3d3xx/camera/amplitude /raw_amplitude:=/o3d3xx/camera/raw_amplitude /depth:=/o3d3xx/camera/depth /confidence:=/o3d3xx/camera/confidence /Dump:=/o3d3xx/camera/Dump __name:=h5writer __log:=/home/dss/.ros/log/73046828-35d4-11e7-81e2-a0c589016c88/o3d3xx_h5-h5writer-2.log].
log file: /home/dss/.ros/log/73046828-35d4-11e7-81e2-a0c589016c88/o3d3xx_h5-h5writer-2*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete

I cannot find o3d3xx.srv among the available code to resolve this error.

**Comment by tpanzarella** [comment]
Sorry. I no longer use/support this software. I've left it on github for those that may still be using it so they have access to the code. For capturing data we just use `rosbag` now (and use scripts to pull out selected messages from the bags into an H5 file when desired).

All of that said, what you are missing is in the pre-requisite package [o3d3xx-ros](https://github.com/lovepark/o3d3xx-ros) This is the ROS node that actually publishes data from the camera so that the H5 node can subscribe and serialize the image/point cloud data to disk.

Again, this code is really unsupported at this point. But I thought I'd lend that pointer. Feel free to fork the code base and use it as a starting point for a new H5 data capture library for o3d3xx cameras.
